# Generated by Django 5.2.2 on 2025-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_inventoryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
