from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name= 'index'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashBoard, name='dashBoard'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('product/', views.product, name='product'),
    path('product/<int:producto_id>/editar/', views.editar_producto, name='editar_producto'),
    path('product/<int:producto_id>/eliminar/', views.eliminar_producto, name='eliminar_producto'),
    path('category/', views.category, name='category'),
    path('category/<int:categoria_id>/editar/', views.editar_categoria, name='editar_categoria'),
    path('category/<int:categoria_id>/eliminar/', views.eliminar_categoria, name='eliminar_categoria'),
    path('sale/', views.sale, name='sale'),
    path('inventory/', views.inventory, name='inventory'),
    path('inventory/<int:inventory_id>/history/', views.inventory_history, name='inventory_history'),
    path('inventory/<int:inventory_id>/restock/', views.restock_inventory, name='restock_inventory'),
    path('customer/', views.customer, name='customer'),
    path('customer/<int:cliente_id>/editar/', views.editar_cliente, name='editar_cliente'),
    path('customer/<int:cliente_id>/eliminar/', views.eliminar_cliente, name='eliminar_cliente'),
    path('employee/', views.employee, name='employee'),
    path('employee/<int:empleado_id>/editar/', views.editar_empleado, name='editar_empleado'),
    path('employee/<int:empleado_id>/eliminar/', views.eliminar_empleado, name='eliminar_empleado'),
    path('supplier/', views.supplier, name='supplier'),
    path('supplier/<int:proveedor_id>/editar/', views.editar_proveedor, name='editar_proveedor'),
    path('supplier/<int:proveedor_id>/eliminar/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('expenses/', views.expenses, name='expenses'),
    path('expenses/<int:expense_id>/edit/', views.edit_expense, name='edit_expense'),
    path('expenses/<int:expense_id>/delete/', views.delete_expense, name='delete_expense'),
    path('ventas/<int:venta_id>/ver/', views.ver_venta, name='ver_venta'),
    path('ventas/<int:venta_id>/eliminar/', views.eliminar_venta, name='eliminar_venta'),
    path('eliminar_producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
    path('eliminar_categoria/<int:categoria_id>/', views.eliminar_categoria, name='eliminar_categoria'),
    path('eliminar_venta/<int:venta_id>/', views.eliminar_venta, name='eliminar_venta'),
    path('eliminar_cliente/<int:customer_id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('eliminar_empleado/<int:empleado_id>/', views.eliminar_empleado, name='eliminar_empleado'),
    path('eliminar_proveedor/<int:proveedor_id>/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('reports/', views.reports, name='reports'),
    path('reports/exportar_ventas_excel/', views.exportar_ventas_excel, name='exportar_ventas_excel'),
    path('reports/exportar_gastos_excel/', views.exportar_gastos_excel, name='exportar_gastos_excel'),
    path('reports/exportar_ventas_mes_excel/<str:mes>/', views.exportar_ventas_mes_excel, name='exportar_ventas_mes_excel'),
    path('reports/exportar_gastos_mes_excel/<str:mes>/', views.exportar_gastos_mes_excel, name='exportar_gastos_mes_excel'),
]